# Generated by Django 5.0.1 on 2026-01-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_legal_consent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='barangay',
        ),
    ]
