# Generated by Django 5.0.1 on 2026-01-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_address_userprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceverification',
            name='photo',
            field=models.FileField(blank=True, upload_to='face_verifications/'),
        ),
    ]
