# Generated by Django 5.0.1 on 2026-01-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric', models.CharField(max_length=80)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'metric')},
            },
        ),
    ]
