# Generated by Django 5.0.1 on 2026-01-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IMPOUNDED', 'Impounded'), ('AVAILABLE', 'Available for Adoption'), ('ADOPTED', 'Adopted'), ('RECLAIMED', 'Reclaimed'), ('RELEASED', 'Released')], default='IMPOUNDED', max_length=20)),
                ('capture_datetime', models.DateTimeField(blank=True, null=True)),
                ('surrender_datetime', models.DateTimeField(blank=True, null=True)),
                ('barangay', models.CharField(blank=True, max_length=120)),
                ('gps_coordinates', models.CharField(blank=True, max_length=120)),
                ('kennel_slot', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
