# Generated by Django 5.0.1 on 2026-01-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age_estimate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dog',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
