# Generated by Django 5.0.1 on 2026-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_dog_age_estimate_dog_name_dog_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='dogs/'),
        ),
    ]
