# Generated by Django 5.0.1 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_color_dog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='vaccination_proof',
            field=models.FileField(blank=True, upload_to='vaccination_proofs/'),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccination_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccination_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccination_status',
            field=models.CharField(
                blank=True,
                choices=[('VACCINATED', 'Vaccinated'), ('UNVACCINATED', 'Unvaccinated')],
                default='',
                max_length=20,
            ),
        ),
    ]
