# Generated by Django 5.0.1 on 2026-01-28 12:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('section', models.CharField(choices=[('SECTION_28', 'Section 28'), ('SECTION_29', 'Section 29'), ('ADDITIONAL', 'Additional')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='penaltycase',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penaltylineitem',
            name='checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='penalties.penaltychecklistitem'),
        ),
    ]
