# Generated by Django 5.0.1 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_contact_name_report_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='location_method',
            field=models.CharField(
                blank=True,
                choices=[('GOOGLE_MAPS', 'Google Maps'), ('MANUAL_ADDRESS', 'Manual Address')],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='maps_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(
                choices=[('STRAY', 'Stray'), ('SURRENDER', 'Surrender'), ('INCIDENT', 'Incident')],
                max_length=20,
            ),
        ),
    ]
