# Generated by Django 5.0.1 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_location_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='location_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('GOOGLE_MAPS', 'Google Maps'),
                    ('MANUAL_ADDRESS', 'Manual Address'),
                    ('BOTH', 'Google Maps + Manual Address'),
                ],
                max_length=20,
            ),
        ),
    ]
