# Generated by Django 5.0.1 on 2026-02-07 00:00

from django.db import migrations, models


def migrate_incident_to_dangerous(apps, schema_editor):
    Report = apps.get_model('reports', 'Report')
    Report.objects.filter(report_type='INCIDENT').update(report_type='DANGEROUS')


def reverse_incident_migration(apps, schema_editor):
    Report = apps.get_model('reports', 'Report')
    Report.objects.filter(report_type='DANGEROUS').update(report_type='INCIDENT')


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_location_method_both'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(
                choices=[
                    ('SURRENDER', 'Surrender Dog'),
                    ('DANGEROUS', 'Dangerous Dog'),
                    ('STRAY', 'Stray Dog'),
                    ('OTHER', 'Other'),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_incident_to_dangerous, reverse_incident_migration),
    ]
