# Generated by Django 4.2.7 on 2026-02-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_contact_email_and_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('STRAY', 'Stray Dog'), ('INJURED', 'Injured Dog'), ('SURRENDER', 'Surrender Dog'), ('DANGEROUS', 'Dangerous Dog'), ('BITE_INCIDENT', 'Bite Incident'), ('ABANDONED', 'Abandoned Dog'), ('WELFARE', 'Welfare Concern'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
