# Generated by Django 5.0.1 on 2026-01-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_type', models.CharField(max_length=120)),
                ('vaccinated_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='dogs.dog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
