# Generated by Django 5.0.1 on 2026-01-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='notified_on_expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='notified_three_days',
            field=models.BooleanField(default=False),
        ),
    ]
