# Generated by Django 4.2.7 on 2026-02-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0002_vaccinationrecord_notified_on_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='from_owner_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccinated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine_type',
            field=models.CharField(blank=True, default='General Vaccine', max_length=120),
        ),
    ]
