# Generated by Django 5.0.1 on 2026-01-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption', '0001_initial'),
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionreservation',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_reservations', to='dogs.dog'),
        ),
    ]
