# Generated by Django 5.0.1 on 2026-01-28 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption', '0002_initial'),
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionreservation',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclaimrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclaim_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclaimrequest',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclaim_requests', to='dogs.dog'),
        ),
        migrations.AddField(
            model_name='reclaimrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclaim_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
