# Generated by Django 5.0.1 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclaimrequest',
            name='reclaim_date',
        ),
        migrations.AddField(
            model_name='reclaimrequest',
            name='ownership_proof',
            field=models.FileField(blank=True, upload_to='reclaim_proofs/'),
        ),
    ]
