# Generated by Django 5.0.1 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_reclaim_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionreservation',
            name='appointment_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionreservation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionreservation',
            name='eligibility_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
